---
title: "Report Pilot CFTR"
author: |
    | "Dario Righelli"
    | "Institute for Applied Mathematics "M.Picone" - CNR"
    | "DISA-MIS - Univeristy of Salerno"
date: "3/6/2018"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(xlsx)

```

# Loading dataset
```{r}
options(stringsAsFactors=FALSE)
dataset <- read.table("../data/CPET_FC_Luglio2018_1.csv", header=TRUE, sep="\t")
ds <- dataset[,-c(1,grep("PRED", colnames(dataset)))]
```

# computing % on mean of patients 
```{r}

#on the mean
dds <- t(as.data.frame(apply(ds, 2, mean)))
post.idx <- grep("POST", colnames(ds))
change.val <- dds[,post.idx] - dds[,post.idx-1]
change.val.percentage <- (change.val/dds[,post.idx-1])*100
change.val.percentage <- t(as.data.frame(change.val.percentage))
colnames(change.val.percentage) <- gsub(".POST", ".Percentage", colnames(change.val.percentage))
write.xlsx(x=change.val.percentage, file="Percentage_Change_Values_on_Means.xls", row.names=FALSE)

change.val.percentage
```

# computing % on each patient
```{r}
#for each patient
post.idx <- grep("POST", colnames(ds))
change.val <- ds[,post.idx] - ds[,post.idx-1]
change.val.percentage <- (change.val/ds[,post.idx-1])*100
colnames(change.val.percentage) <- gsub(".POST", ".Percentage", colnames(change.val.percentage))
rownames(change.val.percentage) <- c(1:3)

write.xlsx(x=change.val.percentage, file="Percentage_Change_Values_on_Patients.xls", row.names=TRUE)

change.val.percentage

```

