---
title: "Report Pilot CFTR"
author: |
  | "Dario Righelli"
  | "Institute for Applied Mathematics "M.Picone" - CNR"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(xlsx)
library(reshape)
library(ggplot2)

```

# Loading dataset Table 1
```{r}
options(stringsAsFactors=FALSE)
dataset <- read.table("data/updated_28_09_18.csv", header=TRUE, sep=";", 
                    dec=".", as.is=TRUE)
ds <- dataset
for(i in 2:dim(ds)[2]) ds[,i]=as.numeric(ds[,i])
```

# computing % on each patient 
```{r}
#for each patient

post.idx <- grep("post", colnames(ds))
change.val <- ds[,post.idx] - ds[,post.idx-1]
change.val.percentage <- (change.val/ds[,post.idx-1])*100
colnames(change.val.percentage) <- c("pat1_%", "pat2_%", "pat3_%")
change.val.percentage$characteristic <- ds$characteristic
change.val.percentage <- change.val.percentage[,c(4,1:3)]
change.val.percentage

```

# Loading dataset Table 2
```{r}
options(stringsAsFactors=FALSE)
dataset <- read.table("data/table3.csv", header=TRUE, sep="\t")
ds <- dataset
for(i in 2:dim(ds)[2]) ds[,i]=as.numeric(ds[,i])
```

# computing % on each patient 
```{r}
#for each patient

post.idx <- grep("post", colnames(ds))
change.val <- ds[,post.idx] - ds[,post.idx-1]
change.val.percentage <- (change.val/ds[,post.idx-1])*100
colnames(change.val.percentage) <- c("pat1_%", "pat2_%", "pat3_%")
change.val.percentage$characteristic <- ds$characteristic
change.val.percentage <- change.val.percentage[,c(4,1:3)]
change.val.percentage

```

# Loading dataset physical
```{r}
options(stringsAsFactors=FALSE)
dataset <- t(read.xlsx("data/Questionario CFQR.xlsx", sheetIndex=1))
ds <- dataset
for(i in 2:dim(ds)[2]) ds[,i]=as.numeric(ds[,i])
```

# computing % on each patient 
```{r}
#for each patient

post.idx <- grep("POST", rownames(ds))
change.val <- ds[post.idx,] - ds[post.idx-1,]
change.val.percentage <- (change.val/ds[post.idx-1,])*100
colnames(change.val.percentage) <- c("pat1_%", "pat2_%", "pat3_%")
rownames(change.val.percentage) <- gsub(pattern=".POST", "", rownames(change.val.percentage))
as.data.frame(change.val.percentage)
```

# Loading dataset for barplots
```{r}

dataset <- read.xlsx("data/CPET  FC 2018 31.5.xlsx", sheetIndex=1, as.data.frame=TRUE, header=TRUE)
colnames(dataset) <- gsub("__", "_", gsub("\\.", "_",colnames(dataset)))
colnames(dataset) <- gsub("X_", "", colnames(dataset))
colnames(dataset) <- gsub("__", "_", colnames(dataset))
colnames(dataset) <- gsub("_$", "", colnames(dataset))
```

# barplots 

Here we plot for each patient his levels of each variable comparing pre and post values.
When a color is not present in a bar, means that the value is 0.

```{r, warning=FALSE, message=FALSE}
idx.pre <- grep(pattern="PRE", x=colnames(dataset))
for(i in idx.pre)
{
    meltedi <- melt(dataset[,c(i, i+1)])
    meltedi$id <- rep(dataset$ID, 2)
    g <- ggplot(meltedi, aes(id)) + geom_bar(mapping=aes(weight=value, fill=variable), data=meltedi, position=position_dodge()) + ggtitle(gsub("_PRE", "", colnames(dataset)[i]))
    print(g)
}
```


